### 默认环境变量配置（直接使用local环境配置）
@baseUrl = http://localhost:48080/admin-api
@adminTenantId = 1
@token = 1e0cc373ac674583a762aeb03c4e7715
@tag = Yunai.local

### 环境配置说明
# 上面已设置默认的local环境变量，可直接运行
# 如需切换环境，请在IntelliJ IDEA中选择对应环境: local/gateway
# 或者手动修改上面的@变量值

### 请求 /login 接口 => 成功（无验证码)
POST {{baseUrl}}/system/auth/login
Content-Type: application/json
tenant-id: {{adminTenantId}}
tag: {{tag}}

{
  "username": "admin",
  "password": "admin123"
}

### 请求 /get-permission-info 接口 => 成功
GET {{baseUrl}}/system/dept/get?id=100
Authorization: Bearer {{token}}
tenant-id: {{adminTenantId}}

### 请求 /get-permission-info 接口 => 成功
POST {{baseUrl}}/system/dept/create
Authorization: Bearer {{token}}
tenant-id: {{adminTenantId}}
Content-Type: application/json

{
  "name": "测试部门4",
  "leaderUserId": "3385310182593531904"
}

### 请求 /get-dept-users 接口 => 成功
GET {{baseUrl}}/system/dept/get-dept-users?deptId=0&keywords=管理
Authorization: Bearer {{token}}
tenant-id: {{adminTenantId}}