import {
  Anchor,
  AnchorRound,
  ArcDeTriomphe,
  AssemblyLine,
  Bad,
  BezierCurve,
  Bike,
  BranchOne,
  BrdigeThree,
  BridgeTwo,
  BulletMap,
  Bye,
  ChangeDateSort,
  ChartGraph,
  ChartHistogram,
  ChinesePavilion,
  ChurchOne,
  CityGate,
  CityOne,
  Clap,
  Come,
  ConceptSharing,
  ConnectionPointTwo,
  Cool,
  DatabaseCode,
  DatabaseDownload,
  DatabaseEnter,
  DatabaseFail,
  DatabaseLock,
  DatabasePosition,
  DatabaseSync,
  DatabaseTime,
  DataDisplay,
  DataLock,
  DataUser,
  Easy,
  Elevator,
  Escalators,
  FactoryBuilding,
  FingerprintTwo,
  Five,
  Flashlight,
  Four,
  Good,
  Gopro,
  HardDiskOne,
  Histogram,
  KagiMap,
  Kettle,
  Gamepad,
  Hdd,
  Lamp,
  Laptop,
  LeftBranch,
  LinkBreak,
  LinkCloudFaild,
  MaslowPyramids,
  Master,
  Memory,
  Microphone,
  MonumentOne,
  Mouse,
  NegativeDynamics,
  NetworkTree,
  Open,
  Pagoda,
  Palace,
  Parabola,
  Phone,
  Phonograph,
  Pie,
  Platte,
  Press,
  School,
  Shop,
  Six,
  Slide,
  Tower,
  Yep,
  Zoom
} from '@icon-park/react';

//应用主题色
export const appThemeColor = ['#009E9E', '#24B28F', '#1979FF', '#7E5AEA', '#EB693A', '#EBBC00'];

// 应用图标
export const appIcon: string[] = [
  'bike',
  'bullet-map',
  'church-one',
  'data-display',
  'fingerprint-two',
  'platte',
  'arc-de-triomphe',
  'brdige-three',
  'bridge-two',
  'chinese-pavilion',
  'city-gate',
  'city-one',
  'elevator',
  'escalators',
  'factory-building',
  'monument-one',
  'link-cloud-faild',
  'network-tree',
  'link-break',
  'left-branch',
  'connection-point-two',
  'branch-one',
  'assembly-line',
  'bezier-curve',
  'anchor-round',
  'anchor',
  'good',
  'four',
  'five',
  'cool',
  'clap',
  'bad',
  'bye',
  'come',
  'easy',
  'concept-sharing',
  'data-lock',
  'database-code',
  'data-user',
  'database-download',
  'database-enter',
  'database-lock',
  'database-position',
  'database-time',
  'database-sync',
  'database-fail',
  'slide',
  'negative-dynamics',
  'parabola',
  'pie',
  'maslow-pyramids',
  'kagi-map',
  'histogram',
  'chart-histogram',
  'chart-graph',
  'change-date-sort',
  'phonograph',
  'phone',
  'mouse',
  'microphone',
  'memory',
  'master',
  'laptop',
  'lamp',
  'kettle',
  'Hdd',
  'gamepad',
  'flashlight',
  'gopro',
  'hardDiskOne',
  'open',
  'press',
  'yep',
  'zoom',
  'six',
  'pagoda',
  'palace',
  'shop',
  'school',
  'tower'
];

export const iconMap = {
  bike: Bike,
  'bullet-map': BulletMap,
  'church-one': ChurchOne,
  'data-display': DataDisplay,
  'fingerprint-two': FingerprintTwo,
  'arc-de-triomphe': ArcDeTriomphe,
  'brdige-three': BrdigeThree,
  'bridge-two': BridgeTwo,
  'chinese-pavilion': ChinesePavilion,
  'city-gate': CityGate,
  'city-one': CityOne,
  elevator: Elevator,
  escalators: Escalators,
  'factory-building': FactoryBuilding,
  'monument-one': MonumentOne,
  'link-cloud-faild': LinkCloudFaild,
  'network-tree': NetworkTree,
  'link-break': LinkBreak,
  'left-branch': LeftBranch,
  'connection-point-two': ConnectionPointTwo,
  'branch-one': BranchOne,
  'assembly-line': AssemblyLine,
  'bezier-curve': BezierCurve,
  'anchor-round': AnchorRound,
  anchor: Anchor,
  good: Good,
  four: Four,
  platte: Platte,
  five: Five,
  cool: Cool,
  clap: Clap,
  bad: Bad,
  bye: Bye,
  come: Come,
  easy: Easy,
  'concept-sharing': ConceptSharing,
  'data-lock': DataLock,
  'database-code': DatabaseCode,
  'data-user': DataUser,
  'database-download': DatabaseDownload,
  'database-enter': DatabaseEnter,
  'database-lock': DatabaseLock,
  'database-position': DatabasePosition,
  'database-time': DatabaseTime,
  'database-sync': DatabaseSync,
  'database-fail': DatabaseFail,
  slide: Slide,
  'negative-dynamics': NegativeDynamics,
  parabola: Parabola,
  pie: Pie,
  'maslow-pyramids': MaslowPyramids,
  'kagi-map': KagiMap,
  histogram: Histogram,
  'chart-histogram': ChartHistogram,
  'chart-graph': ChartGraph,
  'change-date-sort': ChangeDateSort,
  phonograph: Phonograph,
  phone: Phone,
  mouse: Mouse,
  microphone: Microphone,
  memory: Memory,
  master: Master,
  laptop: Laptop,
  lamp: Lamp,
  kettle: Kettle,
  Hdd: Hdd,
  gamepad: Gamepad,
  flashlight: Flashlight,
  gopro: Gopro,
  hardDiskOne: HardDiskOne,
  open: Open,
  press: Press,
  yep: Yep,
  zoom: Zoom,
  six: Six,
  pagoda: Pagoda,
  palace: Palace,
  shop: Shop,
  school: School,
  tower: Tower
} as const;

// 图标背景色
export const appIconColor: string[] = ['#009E9E', '#24B28F', '#1979FF', '#7E5AEA', '#EB693A', '#EBBC00'];

export interface Options {
  label: string;
  value: string;
}
