### 环境配置说明
# 使用全局环境配置文件 http-client.env.json
# 请在IntelliJ IDEA中选择对应环境: local/dev/test/gateway
# 确保先在AuthController.http中登录获取token

### 获得平台信息 /system/platform/get-platform-info
GET {{baseUrl}}/system/platform/get-platform-info
Authorization: Bearer {{token}}

### 获得管理员列表 /admin-api/system/admin-list
GET {{baseUrl}}/system/platform/admin/list
Authorization: Bearer {{token}}
tenant-id: 1
#X-From-Scene-Type: platform

### 获得管理员列表分页 /admin-api/system//admin/page
GET {{baseUrl}}/system/platform/admin/get?id=
Authorization: Bearer {{token}}

### 获得管理员列表分页 /admin-api/system//admin/page
GET {{baseUrl}}/system/platform/admin/page
Content-Type: application/json
Authorization: Bearer {{token}}
timestamp:1765296874000
nonce:KSQjLklkPDFnBEj1
sign:018e5e79e46d93bd9e10f99104e51f1c861c351db948b3125a329e6ccd1bfdee

### 获得管理员列表分页 /admin-api/system//admin/page
POST {{baseUrl}}/system/platform/admin/update-email
Content-Type: application/json
Authorization: Bearer {{token}}
timestamp:1765296874000
nonce:1765293314000
sign:888

{"id":"167086357045215232","email":"155@ss.com"}

### 创建用户 /admin-api/system/user/platform-admin/create
POST {{baseUrl}}/system/platform/admin/create
Content-Type: application/json
Authorization: Bearer {{token}}
tenant-id: 1

{
  "username": "test004",
  "password": "admin123",
  "mobile": "15601691637",
  "email": "test004@qq.com",
  "nickName": "管理员4",
  "adminType": "2"
}

### 查询用户
GET {{baseUrl}}/system/platform/admin/get?id=153539738093060096
Authorization: Bearer {{token}}


