package com.cmsr.onebase.plugin.maven;

import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugin.MojoFailureException;
import org.apache.maven.plugins.annotations.LifecyclePhase;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;
import org.apache.maven.plugins.annotations.ResolutionScope;
import org.apache.maven.project.MavenProject;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;

/**
 * 插件类生成器
 * <p>
 * 自动生成继承 OneBasePlugin 的 GeneratedPlugin 类，
 * 让用户无需了解 PF4J 的 Plugin 类。
 * </p>
 *
 * @author matianyu
 * @date 2025-11-29
 */
@Mojo(
        name = "generate-plugin-class",
        defaultPhase = LifecyclePhase.GENERATE_SOURCES,
        requiresDependencyResolution = ResolutionScope.COMPILE,
        threadSafe = true
)
public class GeneratePluginClassMojo extends AbstractMojo {

    /**
     * Maven项目
     */
    @Parameter(defaultValue = "${project}", readonly = true, required = true)
    private MavenProject project;

    /**
     * 生成源码的输出目录
     */
    @Parameter(defaultValue = "${project.build.directory}/generated-sources/onebase-plugin", required = true)
    private File outputDirectory;

    /**
     * 生成的Plugin类的包名
     */
    @Parameter(property = "generatedPackage", defaultValue = "${project.groupId}")
    private String generatedPackage;

    @Override
    public void execute() throws MojoExecutionException, MojoFailureException {
        getLog().info("生成插件类: " + generatedPackage + ".GeneratedPlugin");

        // 确保输出目录存在
        File packageDir = new File(outputDirectory, generatedPackage.replace('.', '/'));
        if (!packageDir.exists()) {
            packageDir.mkdirs();
        }

        // 生成GeneratedPlugin.java
        generatePluginClass(packageDir);

        // 添加生成的源码目录到项目
        project.addCompileSourceRoot(outputDirectory.getAbsolutePath());
    }

    /**
     * 生成GeneratedPlugin.java
     */
    private void generatePluginClass(File packageDir) throws MojoExecutionException {
        File javaFile = new File(packageDir, "GeneratedPlugin.java");

        try (PrintWriter writer = new PrintWriter(new java.io.OutputStreamWriter(
                new java.io.FileOutputStream(javaFile), java.nio.charset.StandardCharsets.UTF_8))) {
            writer.println("package " + generatedPackage + ";");
            writer.println();
            writer.println("import com.cmsr.onebase.plugin.internal.OneBasePlugin;");
            writer.println("import org.pf4j.PluginWrapper;");
            writer.println();
            writer.println("/**");
            writer.println(" * Auto-generated plugin class");
            writer.println(" * <p>");
            writer.println(" * This class is auto-generated by onebase-plugin-maven-plugin, do not modify manually.");
            writer.println(" * </p>");
            writer.println(" *");
            writer.println(" * @author onebase-plugin-maven-plugin");
            writer.println(" */");
            writer.println("public class GeneratedPlugin extends OneBasePlugin {");
            writer.println();
            writer.println("    /**");
            writer.println("     * Constructor required by PF4J");
            writer.println("     *");
            writer.println("     * @param wrapper plugin wrapper");
            writer.println("     */");
            writer.println("    public GeneratedPlugin(PluginWrapper wrapper) {");
            writer.println("        super(wrapper);");
            writer.println("    }");
            writer.println("}");

            getLog().info("Generated: " + javaFile.getAbsolutePath());
        } catch (IOException e) {
            throw new MojoExecutionException("Failed to generate GeneratedPlugin.java", e);
        }
    }

    // Getter/Setter for testing
    public void setProject(MavenProject project) {
        this.project = project;
    }

    public void setOutputDirectory(File outputDirectory) {
        this.outputDirectory = outputDirectory;
    }

    public void setGeneratedPackage(String generatedPackage) {
        this.generatedPackage = generatedPackage;
    }
}
