import {
  Edit,
  Delete,
  MagicWand,
  WritingFluently,
  MoreApp,
  CheckOne,
  HamburgerButton,
  EditName,
  SettingTwo,
  MoveOne,
  AddFour,
  Repair,
  MoreFour,
  Clear,
  PeoplePlusOne,
  System,
  More,
  AddUser,
  GoOn,
  PeoplePlus,
  Find,
  Add,
  Reject,
  PersonalCollection,
  FullSelection,
  Redo,
  AlignTextMiddleOne,
  SettingOne,
  EditOne,
  EditTwo,
  AddOne,
  Check,
  Translate,
  Right,
  DeleteFour,
  EfferentThree,
  Undo,
  PeopleMinusOne,
  CloseOne,
  Modify,
  DeleteMode,
  DoubleRight,
  PeopleSearch,
  Left,
  EfferentFour,
  AfferentFour,
  AddMode,
  DeleteThree,
  DeleteThemes,
  PlayCycle,
  ShareThree,
  Close,
  AllApplication,
  Share,
  DeleteTwo,
  Like,
  DeleteFive,
  DoubleLeft,
  PeopleMinus,
  Newlybuild,
  DeleteOne,
  Afferent,
  ApplicationTwo,
  Unlike,
  DownloadFour,
  Back,
  UploadOne,
  AfferentThree
} from '@icon-park/react';

export const operationIcon: string[] = [
  'edit',
  'delete',
  'magic-wand',
  'writing-fluently',
  'more-app',
  'check-one',
  'hamburger-button',
  'edit-name',
  'setting-two',
  'move-one',
  'add-four',
  'repair',

  'more-four',
  'clear',
  'people-plus-one',
  'system',
  'more',
  'add-user',
  'go-on',
  'people-plus',
  'find',
  'add',
  'reject',
  'personal-collection',
  'full-selection',
  'redo',
  'align-text-middle-one',
  'setting-one',
  'edit-one',
  'edit-two',
  'add-one',
  'check',
  'translate',
  'right',
  'delete-four',
  'efferent-three',
  'undo',
  'people-minus-one',
  'close-one',
  'modify',
  'delete-mode',
  'double-right',
  'people-search',
  'left',
  'efferent-four',
  'afferent-four',
  'add-mode',
  'delete-three',
  'delete-themes',
  'play-cycle',
  'share-three',
  'close',
  'all-application',
  'share',
  'delete-two',
  'like',
  'delete-five',
  'double-left',
  'people-minus',
  'newlybuild',
  'delete-one',
  'afferent',
  'application-two',
  'unlike',
  'download-four',
  'back',
  'upload-one',
  'afferent-three'
];

export const iconMap = {
  'edit': Edit,
  'delete': Delete,
  'magic-wand': MagicWand,
  'writing-fluently': WritingFluently,
  'more-app': MoreApp,
  'check-one': CheckOne,
  'hamburger-button': HamburgerButton,
  'edit-name': EditName,
  'setting-two': SettingTwo,
  'move-one': MoveOne,
  'add-four': AddFour,
  'repair': Repair,
  'more-four': MoreFour,
  'clear': Clear,
  'people-plus-one': PeoplePlusOne,
  'system': System,
  'more': More,
  'add-user': AddUser,
  'go-on': GoOn,
  'people-plus': PeoplePlus,
  'find': Find,
  'add': Add,
  'reject': Reject,
  'personal-collection': PersonalCollection,
  'full-selection': FullSelection,
  'redo': Redo,
  'align-text-middle-one': AlignTextMiddleOne,
  'setting-one': SettingOne,
  'edit-one': EditOne,
  'edit-two': EditTwo,
  'add-one': AddOne,
  'check': Check,
  'translate': Translate,
  'right': Right,
  'delete-four': DeleteFour,
  'efferent-three': EfferentThree,
  'undo': Undo,
  'people-minus-one': PeopleMinusOne,
  'close-one': CloseOne,
  'modify': Modify,
  'delete-mode': DeleteMode,
  'double-right': DoubleRight,
  'people-search': PeopleSearch,
  'left': Left,
  'efferent-four': EfferentFour,
  'afferent-four': AfferentFour,
  'add-mode': AddMode,
  'delete-three': DeleteThree,
  'delete-themes': DeleteThemes,
  'play-cycle': PlayCycle,
  'share-three': ShareThree,
  'close': Close,
  'all-application': AllApplication,
  'share': Share,
  'delete-two': DeleteTwo,
  'like': Like,
  'delete-five': DeleteFive,
  'double-left': DoubleLeft,
  'people-minus': PeopleMinus,
  'newlybuild': Newlybuild,
  'delete-one': DeleteOne,
  'afferent': Afferent,
  'application-two': ApplicationTwo,
  'unlike': Unlike,
  'download-four': DownloadFour,
  'back': Back,
  'upload-one': UploadOne,
  'afferent-three': AfferentThree
} as const;

export const iconColorList = ['#4E5969', '#00B42A', '#F53F3F', '#165DFF', '#FF7D00', '#C9CDD4'];