package ${package};

import com.cmsr.onebase.plugin.api.HttpHandler;
import com.cmsr.onebase.plugin.service.PluginContextService;
import jakarta.annotation.Resource;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import java.util.Map;

/**
 * 插件上下文服务演示 Controller
 * <p>
 * 演示如何在插件中使用 PluginContextService 读取和管理动态配置参数。
 * </p>
 *
 * @author Generated by OneBase Plugin Archetype
 * @date 2026-01-10
 */
@RestController
@RequestMapping("/plugin/${artifactId}/context")
public class ContextDemoController implements HttpHandler {

    private static final DateTimeFormatter FORMATTER = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");

    @Resource
    private PluginContextService pluginContextService;

    /**
     * 获取所有配置
     * <p>
     * 示例：GET /plugin/${artifactId}/context/all
     * </p>
     */
    @GetMapping("/all")
    public ResponseEntity<Map<String, Object>> getAllConfig() {
        Map<String, Object> result = new HashMap<>();
        result.put("pluginId", getPluginId());
        result.put("pluginVersion", getPluginVersion());
        result.put("config", pluginContextService.getConfig(getPluginId(), getPluginVersion()));
        result.put("timestamp", LocalDateTime.now().format(FORMATTER));

        return ResponseEntity.ok(result);
    }

    /**
     * 获取租户ID
     * <p>
     * 示例：GET /plugin/${artifactId}/context/tenant-id
     * </p>
     */
    @GetMapping("/tenant-id")
    public ResponseEntity<Map<String, Object>> getCurrentTenantId() {
        Long tenantId = pluginContextService.getTenantId();

        Map<String, Object> result = new HashMap<>();
        result.put("tenantId", tenantId);
        result.put("timestamp", LocalDateTime.now().format(FORMATTER));

        return ResponseEntity.ok(result);
    }

    /**
     * 获取指定配置项
     * <p>
     * 示例：GET /plugin/${artifactId}/context/key/apiKey
     * </p>
     */
    @GetMapping("/key/{key}")
    public ResponseEntity<Map<String, Object>> getConfigValue(@PathVariable String key) {
        Object value = pluginContextService.getConfigValue(getPluginId(), getPluginVersion(), key);

        Map<String, Object> result = new HashMap<>();
        result.put("key", key);
        result.put("value", value);
        result.put("exists", pluginContextService.hasConfigKey(getPluginId(), getPluginVersion(), key));
        result.put("timestamp", LocalDateTime.now().format(FORMATTER));

        return ResponseEntity.ok(result);
    }

    /**
     * 配置应用演示
     * <p>
     * 演示如何在实际业务中使用配置参数。
     * 示例：GET /plugin/${artifactId}/context/demo
     * </p>
     */
    @GetMapping("/demo")
    public ResponseEntity<Map<String, Object>> configDemo() {
        // 读取各种类型的配置
        String apiKey = pluginContextService.getConfigValue(getPluginId(), getPluginVersion(), "apiKey", "default-key");
        String provider = pluginContextService.getConfigValue(getPluginId(), getPluginVersion(), "provider", "unknown");
        Integer timeout = pluginContextService.getConfigValue(getPluginId(), getPluginVersion(), "timeout", 3000);
        Boolean enableLog = pluginContextService.getConfigValue(getPluginId(), getPluginVersion(), "enableLog", false);

        // 模拟业务逻辑
        Map<String, Object> businessResult = new HashMap<>();
        businessResult.put("message", "配置应用演示");
        businessResult.put("provider", provider);
        businessResult.put("apiKeyConfigured", !apiKey.equals("default-key"));
        businessResult.put("timeout", timeout + "ms");
        businessResult.put("logEnabled", enableLog);

        if (enableLog) {
            businessResult.put("log", String.format("[%s] 使用 %s 服务，超时时间: %dms",
                    LocalDateTime.now().format(FORMATTER), provider, timeout));
        }

        return ResponseEntity.ok(businessResult);
    }

    /**
     * 配置信息总览
     * <p>
     * 示例：GET /plugin/${artifactId}/context/info
     * </p>
     */
    @GetMapping("/info")
    public ResponseEntity<Map<String, Object>> configInfo() {
        Map<String, Object> allConfig = pluginContextService.getConfig(getPluginId(), getPluginVersion());

        Map<String, Object> info = new HashMap<>();
        info.put("pluginId", getPluginId());
        info.put("pluginVersion", getPluginVersion());
        info.put("configCount", allConfig.size());
        info.put("configKeys", allConfig.keySet());
        info.put("timestamp", LocalDateTime.now().format(FORMATTER));

        return ResponseEntity.ok(info);
    }
}
