package ${package};

import cn.hutool.crypto.SecureUtil;
import cn.hutool.crypto.digest.DigestUtil;
import cn.hutool.crypto.symmetric.AES;
import com.cmsr.onebase.plugin.api.HttpHandler;
import lombok.extern.slf4j.Slf4j;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.util.HtmlUtils;

import java.nio.charset.StandardCharsets;
import java.util.HashMap;
import java.util.Map;

/**
 * Hutool 加密演示 Controller
 * <p>
 * 演示如何在插件中使用第三方依赖（Hutool），验证依赖能否被正确打包到 ZIP 并被 PF4J 加载。
 * </p>
 *
 * @author Generated by OneBase Plugin Archetype
 * @date 2026-01-10
 */
@RestController
@Slf4j
@RequestMapping("/plugin/${artifactId}/crypto")
public class HutoolCryptoController implements HttpHandler {

    /**
     * 测试 Hutool 加密功能
     * <p>
     * 访问路径：GET /plugin/${artifactId}/crypto/test?text=xxx
     * </p>
     */
    @GetMapping("/test")
    public Map<String, Object> cryptoTest(@RequestParam(defaultValue = "Hello OneBase Plugin") String text) {
        Map<String, Object> result = new HashMap<>();

        try {
            // 1. MD5加密
            String md5 = DigestUtil.md5Hex(text);
            result.put("md5", md5);

            // 2. SHA256加密
            String sha256 = DigestUtil.sha256Hex(text);
            result.put("sha256", sha256);

            // 3. AES加密
            String key = "onebase123456789"; // 16字节密钥（AES-128）
            AES aes = SecureUtil.aes(key.getBytes(StandardCharsets.UTF_8));
            String encrypted = aes.encryptHex(text);
            result.put("aesEncrypted", encrypted);

            // 4. AES解密验证
            String decrypted = aes.decryptStr(encrypted);
            result.put("aesDecrypted", decrypted);
            result.put("aesVerified", text.equals(decrypted));

            // 5. 原始文本
            result.put("originalText", text);

            // 6. 插件信息
            result.put("pluginId", "${artifactId}");
            result.put("message", "Hutool 三方依赖加载成功！AES 加密解密验证通过！");
            result.put("success", true);

            log.info("Hutool 依赖加载成功！");
        } catch (Exception e) {
            result.put("success", false);
            // XSS 转义异常消息，防止跨站脚本攻击
            result.put("error", HtmlUtils.htmlEscape(e.getMessage()));
            result.put("errorType", HtmlUtils.htmlEscape(e.getClass().getName()));
            log.error("Hutool 依赖加载失败！", e);
        }

        return result;
    }

    /**
     * 检查 Hutool 是否可用
     * <p>
     * 访问路径：GET /plugin/${artifactId}/crypto/check
     * </p>
     */
    @GetMapping("/check")
    public Map<String, Object> checkHutool() {
        Map<String, Object> result = new HashMap<>();

        try {
            // 尝试加载 Hutool 类
            Class<?> clazz = Class.forName("cn.hutool.crypto.SecureUtil");
            result.put("hutoolClassLoaded", true);
            result.put("hutoolClassName", clazz.getName());
            result.put("classLoader", clazz.getClassLoader().getClass().getName());

            // 测试简单功能
            String testMd5 = DigestUtil.md5Hex("test");
            result.put("testMd5", testMd5);
            result.put("md5Correct", "098f6bcd4621d373cade4e832627b4f6".equals(testMd5));

            result.put("message", "Hutool 依赖检查通过！");
            result.put("success", true);

        } catch (ClassNotFoundException e) {
            result.put("hutoolClassLoaded", false);
            // XSS 转义异常消息，防止跨站脚本攻击
            result.put("error", HtmlUtils.htmlEscape("Hutool 类未找到: " + e.getMessage()));
            result.put("success", false);
        } catch (Exception e) {
            // XSS 转义异常消息，防止跨站脚本攻击
            result.put("error", HtmlUtils.htmlEscape(e.getMessage()));
            result.put("errorType", HtmlUtils.htmlEscape(e.getClass().getName()));
            result.put("success", false);
        }

        return result;
    }
}
