spring:
  application:
    name: metadata-runtime
  profiles:
    active: local
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

server:
  port: 48081

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
