import { ENTITY_FIELD_TYPE, FORM_COMPONENT_TYPES } from '@onebase/ui-kit';

// 组件类型与组件实现的映射表
export const COMPONENT_MAP: Record<string, string> = {
  [ENTITY_FIELD_TYPE.TEXT.VALUE]: FORM_COMPONENT_TYPES.INPUT_TEXT,
  [ENTITY_FIELD_TYPE.LONG_TEXT.VALUE]: FORM_COMPONENT_TYPES.INPUT_TEXTAREA,
  [ENTITY_FIELD_TYPE.EMAIL.VALUE]: FORM_COMPONENT_TYPES.INPUT_EMAIL,
  [ENTITY_FIELD_TYPE.PHONE.VALUE]: FORM_COMPONENT_TYPES.INPUT_PHONE,
  [ENTITY_FIELD_TYPE.URL.VALUE]: FORM_COMPONENT_TYPES.INPUT_TEXT,
  [ENTITY_FIELD_TYPE.ADDRESS.VALUE]: FORM_COMPONENT_TYPES.INPUT_TEXT,
  [ENTITY_FIELD_TYPE.NUMBER.VALUE]: FORM_COMPONENT_TYPES.INPUT_NUMBER,
  [ENTITY_FIELD_TYPE.CURRENCY.VALUE]: FORM_COMPONENT_TYPES.INPUT_NUMBER,
  [ENTITY_FIELD_TYPE.DATE.VALUE]: FORM_COMPONENT_TYPES.DATE_PICKER,
  [ENTITY_FIELD_TYPE.DATETIME.VALUE]: FORM_COMPONENT_TYPES.DATE_TIME_PICKER,
  [ENTITY_FIELD_TYPE.TIME.VALUE]: FORM_COMPONENT_TYPES.TIME_PICKER,
  [ENTITY_FIELD_TYPE.BOOLEAN.VALUE]: FORM_COMPONENT_TYPES.SWITCH,
  [ENTITY_FIELD_TYPE.SELECT.VALUE]: FORM_COMPONENT_TYPES.SELECT_ONE,
  [ENTITY_FIELD_TYPE.MULTI_SELECT.VALUE]: FORM_COMPONENT_TYPES.SELECT_MUTIPLE,
  [ENTITY_FIELD_TYPE.AUTO_CODE.VALUE]: FORM_COMPONENT_TYPES.AUTO_CODE,
  [ENTITY_FIELD_TYPE.USER.VALUE]: FORM_COMPONENT_TYPES.USER_SELECT,
  [ENTITY_FIELD_TYPE.DEPARTMENT.VALUE]: FORM_COMPONENT_TYPES.DEPT_SELECT,

  //   TODO(Mickey): 补充对应组件
  [ENTITY_FIELD_TYPE.DATA_SELECTION.VALUE]: FORM_COMPONENT_TYPES.INPUT_TEXT,
  [ENTITY_FIELD_TYPE.RELATION.VALUE]: FORM_COMPONENT_TYPES.RELATED_FORM,
  //   TODO(Mickey): 补充对应组件
  [ENTITY_FIELD_TYPE.STRUCTURE.VALUE]: FORM_COMPONENT_TYPES.INPUT_TEXT,
  //   TODO(Mickey): 补充对应组件
  [ENTITY_FIELD_TYPE.ARRAY.VALUE]: FORM_COMPONENT_TYPES.INPUT_TEXT,
  [ENTITY_FIELD_TYPE.FILE.VALUE]: FORM_COMPONENT_TYPES.FILE_UPLOAD,
  [ENTITY_FIELD_TYPE.IMAGE.VALUE]: FORM_COMPONENT_TYPES.IMG_UPLOAD,
  //   TODO(Mickey): 补充对应组件
  [ENTITY_FIELD_TYPE.GEOGRAPHY.VALUE]: FORM_COMPONENT_TYPES.INPUT_TEXT,
  [ENTITY_FIELD_TYPE.PASSWORD.VALUE]: FORM_COMPONENT_TYPES.INPUT_TEXT,
  //   TODO(Mickey): 补充对应组件
  [ENTITY_FIELD_TYPE.ENCRYPTED.VALUE]: FORM_COMPONENT_TYPES.INPUT_TEXT,
  //   TODO(Mickey): 补充对应组件
  [ENTITY_FIELD_TYPE.AGGREGATE.VALUE]: FORM_COMPONENT_TYPES.INPUT_TEXT,
  [ENTITY_FIELD_TYPE.ID.VALUE]: FORM_COMPONENT_TYPES.INPUT_TEXT
};
