import { ENTITY_FIELD_TYPE_LABEL } from "@/pages/CreateApp/pages/DataFactory/utils/const";
import { FORM_COMPONENT_TYPES } from "@onebase/ui-kit";

// 组件类型与组件实现的映射表
export const COMPONENT_MAP: Record<string, string> = {
    [ENTITY_FIELD_TYPE_LABEL.TEXT]: FORM_COMPONENT_TYPES.INPUT_TEXT,
    [ENTITY_FIELD_TYPE_LABEL.LONG_TEXT]: FORM_COMPONENT_TYPES.INPUT_TEXTAREA,
    [ENTITY_FIELD_TYPE_LABEL.EMAIL]: FORM_COMPONENT_TYPES.INPUT_EMAIL,
    [ENTITY_FIELD_TYPE_LABEL.PHONE]: FORM_COMPONENT_TYPES.INPUT_PHONE,
    [ENTITY_FIELD_TYPE_LABEL.URL]: FORM_COMPONENT_TYPES.INPUT_TEXT,
    [ENTITY_FIELD_TYPE_LABEL.ADDRESS]: FORM_COMPONENT_TYPES.INPUT_TEXT,
    [ENTITY_FIELD_TYPE_LABEL.NUMBER]: FORM_COMPONENT_TYPES.INPUT_NUMBER,
    [ENTITY_FIELD_TYPE_LABEL.CURRENCY]: FORM_COMPONENT_TYPES.INPUT_NUMBER,
    [ENTITY_FIELD_TYPE_LABEL.DATE]: FORM_COMPONENT_TYPES.DATE_PICKER,
    [ENTITY_FIELD_TYPE_LABEL.DATETIME]: FORM_COMPONENT_TYPES.DATE_TIME_PICKER,
    [ENTITY_FIELD_TYPE_LABEL.BOOLEAN]: FORM_COMPONENT_TYPES.SWITCH,
    [ENTITY_FIELD_TYPE_LABEL.PICKLIST]: FORM_COMPONENT_TYPES.SELECT_ONE,
    [ENTITY_FIELD_TYPE_LABEL.MULTI_PICKLIST]: FORM_COMPONENT_TYPES.SELECT_MUTIPLE,
    [ENTITY_FIELD_TYPE_LABEL.AUTO_CODE]: FORM_COMPONENT_TYPES.AUTO_CODE,
    [ENTITY_FIELD_TYPE_LABEL.AUTO_NUMBER]: FORM_COMPONENT_TYPES.AUTO_NUMBER,
    [ENTITY_FIELD_TYPE_LABEL.USER]: FORM_COMPONENT_TYPES.USER_SELECT,
    [ENTITY_FIELD_TYPE_LABEL.DEPARTMENT]: FORM_COMPONENT_TYPES.DEPT_SELECT,
    [ENTITY_FIELD_TYPE_LABEL.DATA_SELECTION]: FORM_COMPONENT_TYPES.RELATED_FORM,
    // [ENTITY_FIELD_TYPE_LABEL.STRUCTURE]: FORM_COMPONENT_TYPES.INPUT_TEXT,
    // [ENTITY_FIELD_TYPE_LABEL.ARRAY]: undefined,
    [ENTITY_FIELD_TYPE_LABEL.FILE]: FORM_COMPONENT_TYPES.FILE_UPLOAD,
    [ENTITY_FIELD_TYPE_LABEL.IMAGE]: FORM_COMPONENT_TYPES.IMG_UPLOAD,
    // [ENTITY_FIELD_TYPE_LABEL.GEOGRAPHY]: FORM_COMPONENT_TYPES.INPUT_TEXT,
    [ENTITY_FIELD_TYPE_LABEL.PASSWORD]: FORM_COMPONENT_TYPES.INPUT_TEXT,
    // [ENTITY_FIELD_TYPE_LABEL.ENCRYPTED]: undefined,
    // [ENTITY_FIELD_TYPE_LABEL.AGGREGATE]: undefined,
};
