import { ENTITY_FIELD_TYPE } from '@/components/DataFactory';
import { FORM_COMPONENT_TYPES } from '@/components/Materials/componentTypes';

// 组件类型与组件实现的映射表
export const COMPONENT_MAP: Record<string, string> = {
  [ENTITY_FIELD_TYPE.TEXT.VALUE]: FORM_COMPONENT_TYPES.INPUT_TEXT,
  [ENTITY_FIELD_TYPE.LONG_TEXT.VALUE]: FORM_COMPONENT_TYPES.INPUT_TEXTAREA,
  [ENTITY_FIELD_TYPE.EMAIL.VALUE]: FORM_COMPONENT_TYPES.INPUT_EMAIL,
  [ENTITY_FIELD_TYPE.PHONE.VALUE]: FORM_COMPONENT_TYPES.INPUT_PHONE,
  [ENTITY_FIELD_TYPE.URL.VALUE]: FORM_COMPONENT_TYPES.INPUT_TEXT,
  [ENTITY_FIELD_TYPE.ADDRESS.VALUE]: FORM_COMPONENT_TYPES.INPUT_TEXT,
  [ENTITY_FIELD_TYPE.NUMBER.VALUE]: FORM_COMPONENT_TYPES.INPUT_NUMBER,
  [ENTITY_FIELD_TYPE.DATE.VALUE]: FORM_COMPONENT_TYPES.DATE_PICKER,
  [ENTITY_FIELD_TYPE.DATETIME.VALUE]: FORM_COMPONENT_TYPES.DATE_TIME_PICKER,
  [ENTITY_FIELD_TYPE.TIME.VALUE]: FORM_COMPONENT_TYPES.TIME_PICKER,
  [ENTITY_FIELD_TYPE.BOOLEAN.VALUE]: FORM_COMPONENT_TYPES.SWITCH,
  [ENTITY_FIELD_TYPE.SELECT.VALUE]: FORM_COMPONENT_TYPES.SELECT_ONE,
  [ENTITY_FIELD_TYPE.MULTI_SELECT.VALUE]: FORM_COMPONENT_TYPES.SELECT_MUTIPLE,
  [ENTITY_FIELD_TYPE.AUTO_CODE.VALUE]: FORM_COMPONENT_TYPES.AUTO_CODE,
  [ENTITY_FIELD_TYPE.USER.VALUE]: FORM_COMPONENT_TYPES.USER_SELECT,
  [ENTITY_FIELD_TYPE.DEPARTMENT.VALUE]: FORM_COMPONENT_TYPES.DEPT_SELECT,
  [ENTITY_FIELD_TYPE.DATA_SELECTION.VALUE]: FORM_COMPONENT_TYPES.DATA_SELECT,
  [ENTITY_FIELD_TYPE.FILE.VALUE]: FORM_COMPONENT_TYPES.FILE_UPLOAD,
  [ENTITY_FIELD_TYPE.IMAGE.VALUE]: FORM_COMPONENT_TYPES.IMG_UPLOAD,

  // TODO(Mickey) 地理位置
  [ENTITY_FIELD_TYPE.GEOGRAPHY.VALUE]: FORM_COMPONENT_TYPES.INPUT_TEXT,
  // TODO(Mickey) 密码
  [ENTITY_FIELD_TYPE.PASSWORD.VALUE]: FORM_COMPONENT_TYPES.INPUT_TEXT,
  // TODO(Mickey) 加密字段
  [ENTITY_FIELD_TYPE.ENCRYPTED.VALUE]: FORM_COMPONENT_TYPES.INPUT_TEXT,
  // TODO(Mickey) 聚合统计
  [ENTITY_FIELD_TYPE.AGGREGATE.VALUE]: FORM_COMPONENT_TYPES.INPUT_TEXT,
  // TODO(Mickey) 唯一标识
  [ENTITY_FIELD_TYPE.ID.VALUE]: FORM_COMPONENT_TYPES.INPUT_TEXT,
  // 用户多选
  [ENTITY_FIELD_TYPE.MULTI_USER.VALUE]: FORM_COMPONENT_TYPES.USER_MULTIPLE_SELECT,
  // 部门多选
  [ENTITY_FIELD_TYPE.MULTI_DEPARTMENT.VALUE]: FORM_COMPONENT_TYPES.DEPT_MULTIPLE_SELECT,
  // 数据选择
  [ENTITY_FIELD_TYPE.MULTI_DATA_SELECTION.VALUE]: FORM_COMPONENT_TYPES.DATA_SELECT
};

// 组件类型与数据字段配置可选择字段类型的映射表  fieldType TEXT
export const COMPONENT_FIELD_MAP: Record<string, string[]> = {
  // 单行文本 XInputText =>  常规文本、长文本内容
  [FORM_COMPONENT_TYPES.INPUT_TEXT]: [ENTITY_FIELD_TYPE.TEXT.VALUE, ENTITY_FIELD_TYPE.LONG_TEXT.VALUE],
  // 多行文本  XInputTextArea => 常规文本、长文本内容
  [FORM_COMPONENT_TYPES.INPUT_TEXTAREA]: [ENTITY_FIELD_TYPE.TEXT.VALUE, ENTITY_FIELD_TYPE.LONG_TEXT.VALUE],
  // 富文本  XRichText => 常规文本
  [FORM_COMPONENT_TYPES.RICH_TEXT]: [ENTITY_FIELD_TYPE.TEXT.VALUE, ENTITY_FIELD_TYPE.LONG_TEXT.VALUE],
  // 邮箱 XInputEmail => 邮箱
  [FORM_COMPONENT_TYPES.INPUT_EMAIL]: [ENTITY_FIELD_TYPE.EMAIL.VALUE],
  // 电话 XInputPhone => 电话
  [FORM_COMPONENT_TYPES.INPUT_PHONE]: [ENTITY_FIELD_TYPE.PHONE.VALUE],
  // 数字录入 XInputNumber => 数字
  [FORM_COMPONENT_TYPES.INPUT_NUMBER]: [ENTITY_FIELD_TYPE.NUMBER.VALUE],
  // 日期 XDatePicker => 日期
  [FORM_COMPONENT_TYPES.DATE_PICKER]: [ENTITY_FIELD_TYPE.DATE.VALUE],
  // 日期区间 XDatePicker => 无
  [FORM_COMPONENT_TYPES.DATE_RANGE_PICKER]: [],
  // 日期时间 XTimePicker => 日期时间
  [FORM_COMPONENT_TYPES.DATE_TIME_PICKER]: [ENTITY_FIELD_TYPE.DATETIME.VALUE],
  // 时间 XTimePicker => 时间、日期时间
  [FORM_COMPONENT_TYPES.TIME_PICKER]: [ENTITY_FIELD_TYPE.TIME.VALUE, ENTITY_FIELD_TYPE.DATETIME.VALUE],
  // 开关 XSwitch => 开关
  [FORM_COMPONENT_TYPES.SWITCH]: [ENTITY_FIELD_TYPE.BOOLEAN.VALUE],
  // 单选框 XRadio => 单选框、下拉单选
  [FORM_COMPONENT_TYPES.RADIO]: [ENTITY_FIELD_TYPE.RADIO.VALUE, ENTITY_FIELD_TYPE.SELECT.VALUE],
  // 复选框 XCheckbox => 复选框、下拉多选
  [FORM_COMPONENT_TYPES.CHECKBOX]: [ENTITY_FIELD_TYPE.CHECKBOX.VALUE, ENTITY_FIELD_TYPE.MULTI_SELECT.VALUE],
  // 下拉单选 XSelectOne => 单选框、下拉单选
  [FORM_COMPONENT_TYPES.SELECT_ONE]: [ENTITY_FIELD_TYPE.RADIO.VALUE, ENTITY_FIELD_TYPE.SELECT.VALUE],
  // 下拉多选 XSelectMutiple => 复选框、下拉多选
  [FORM_COMPONENT_TYPES.SELECT_MUTIPLE]: [ENTITY_FIELD_TYPE.CHECKBOX.VALUE, ENTITY_FIELD_TYPE.MULTI_SELECT.VALUE],
  // 人员选择 XUserSelect => 人员
  [FORM_COMPONENT_TYPES.USER_SELECT]: [ENTITY_FIELD_TYPE.USER.VALUE],
  // 人员多选 XUserMultipleSelect => 人员多选
  [FORM_COMPONENT_TYPES.USER_MULTIPLE_SELECT]: [ENTITY_FIELD_TYPE.MULTI_USER.VALUE],
  // 部门选择 XDeptSelect => 部门
  [FORM_COMPONENT_TYPES.DEPT_SELECT]: [ENTITY_FIELD_TYPE.DEPARTMENT.VALUE],
  // 部门多选 XDeptSelect => 部门多选
  [FORM_COMPONENT_TYPES.DEPT_MULTIPLE_SELECT]: [ENTITY_FIELD_TYPE.MULTI_DEPARTMENT.VALUE],
  // 文件上传 XFileUpload => 文件、图片
  [FORM_COMPONENT_TYPES.FILE_UPLOAD]: [ENTITY_FIELD_TYPE.FILE.VALUE, ENTITY_FIELD_TYPE.IMAGE.VALUE],
  // 图片上传 XImgUpload => 图片
  [FORM_COMPONENT_TYPES.IMG_UPLOAD]: [ENTITY_FIELD_TYPE.IMAGE.VALUE],
  // 自动编号 XAutoCode => 自动编号
  [FORM_COMPONENT_TYPES.AUTO_CODE]: [ENTITY_FIELD_TYPE.AUTO_CODE.VALUE],
  // 关联表单 XRelatedForm => 关联表单
  [FORM_COMPONENT_TYPES.RELATED_FORM]: [ENTITY_FIELD_TYPE.RELATION.VALUE],
  // 轮播图 XCarouselForm => 无
  [FORM_COMPONENT_TYPES.CAROUSEL_FORM]: [],
  // 子表单 XSubTable => 无
  [FORM_COMPONENT_TYPES.SUB_TABLE]: [],
  //数据选择XDataSelect => 数据选择
  [FORM_COMPONENT_TYPES.DATA_SELECT]: [ENTITY_FIELD_TYPE.DATA_SELECTION.VALUE]
};
