# OneBase 后端 Upstream 定义
# 放在 http 块中引用: include /path/to/onebase-upstream.conf;

upstream onebase-build {
    server onebase-server-build:8080;
    keepalive 32;
}

upstream onebase-runtime {
    server onebase-server-runtime:8080;
    keepalive 32;
}

upstream onebase-flink {
    server onebase-server-flink:8080;
    keepalive 16;
}