### 获取租户编号 /admin-api/system/get-id-by-name
GET http://127.0.0.1:48080/admin-api/system/user/simple-list
Authorization: Bearer eb33f553e1194b52935de6fcc6a3f4f5

### 创建用户 /admin-api/system/user/platform-admin/create
POST http://127.0.0.1:48080/admin-api/system/user/platform-admin/create
Content-Type: application/json
Authorization: Bearer 49f113f25a9f45f99053feb37f56c5d4
tenant-id: 1

{
  "username": "adminzhou1",
  "password": "admin123",
  "mobile": "15601691324",
  "email": "13524@qq.com",
  "userType": "2"
}
### 根据状态查询用户信息列表 /admin-api/system/user/platform-admin/list
GET http://127.0.0.1:48080/admin-api/system/user/platform-admin/list
Content-Type: application/json
Authorization: Bearer 1c274ed6c3a04877814c315ea207b39c

### 修改租户 /admin-api/system/user/platform-admin/update-email
POST http://127.0.0.1:48080/admin-api/system/user/platform-admin/update-email
Content-Type: application/json
Authorization: Bearer 9fc027e30ea244a28ccc6c0c90743783
tenant-id: 1

{
  "id": 3385319841891094528,
  "email": "13578@qq.com"
}

### 修改平台管理员密码 /admin-api/system/user/platform-admin/update-password
POST http://127.0.0.1:48080/admin-api/system/user/platform-admin/update-password
Content-Type: application/json
Authorization: Bearer ade173b1245541f880c7812cfadadbdf
tenant-id: 1

{
  "id": "3385319841891094528",
  "password": "admin124"
}

### 删除平台管理员用户 /system/user/platform-admin/delete
DELETE http://127.0.0.1:48080/admin-api/system/user/platform-admin/delete
Content-Type: application/json
Authorization: Bearer 91dda3f8eb2d46a780b73c529f1c94e8
tenant-id: 1

{
  "id": 3385344712104742912
}

### 平台管理员列表查询 /system/user/platform-admin/list
GET http://127.0.0.1:48080/admin-api/system/user/platform-admin/list
Content-Type: application/json
Authorization: Bearer 3dac9549902340338047f498ae0b8b18
tenant-id: 1

### 平台管理员分页列表查询 /system/user/platform-admin/page
GET http://127.0.0.1:48080/admin-api/system/user/platform-admin/page?keyword=goudan&pageNum=1&pageSize=10
Content-Type: application/json
Authorization: Bearer b70021cab5df45e0b86c3af58fd16acc
tenant-id: 1
