### 获取租户编号 /admin-api/system/get-id-by-name
GET http://127.0.0.1:48080/admin-api/system/user/simple-list
Authorization: Bearer eb33f553e1194b52935de6fcc6a3f4f5

### 创建用户 /admin-api/system/user/platform-admin/create
POST http://127.0.0.1:48080/admin-api/system/user/platform-admin/create
Content-Type: application/json
Authorization: Bearer d6c2b8f9cc18459aa544a52cdfb5b1b0
tenant-id: 1

{
  "username": "admin3",
  "password": "admin123",
  "mobile": "15601691313",
  "email": "13573@qq.com",
  "userType": "2"
}
### 根据状态查询用户信息列表 /admin-api/system/user/platform-admin/list
GET http://127.0.0.1:48080/admin-api/system/user/platform-admin/list
Content-Type: application/json
Authorization: Bearer 1c274ed6c3a04877814c315ea207b39c

### 修改租户 /admin-api/system/tenant/create
PUT http://127.0.0.1:48080/admin-api/system/user/platform-admin/update
Content-Type: application/json
Authorization: Bearer 91dda3f8eb2d46a780b73c529f1c94e8
tenant-id: 1

{
  "id": 3385319841891094528,
  "email": "13577@qq.com"
}

### 修改平台用户密码 /admin-api/system/tenant/create
PUT http://127.0.0.1:48080/admin-api/system/user/update-platform-password
Content-Type: application/json
Authorization: Bearer 91dda3f8eb2d46a780b73c529f1c94e8
tenant-id: 1

{
  "id": 3385319841891094528,
  "password": "123124"
}

### 修改平台用户密码 /admin-api/system/tenant/delete
DELETE http://127.0.0.1:48080/admin-api/system/user/platform-admin/delete
Content-Type: application/json
Authorization: Bearer 91dda3f8eb2d46a780b73c529f1c94e8
tenant-id: 1

{
  "id": 3385344712104742912
}