### 获取租户编号 /admin-api/system/get-id-by-name
GET http://127.0.0.1:48080/admin-api/system/tenant/simple-list
Authorization: Bearer eb33f553e1194b52935de6fcc6a3f4f5
### 创建租户 /admin-api/system/tenant/create
POST http://127.0.0.1:48080/admin-api/system/tenant/create
Content-Type: application/json
Authorization: Bearer fe416b951aa24e21ac721bc65794ca6b
tenant-id: 1

{
  "name": "租户19",
  "accountCount": "10",
  "contactName": "test19",
  "status": 0
}

### 更新租户 /admin-api/system/tenant/update
POST http://127.0.0.1:48080/admin-api/system/tenant/update
Content-Type: application/json
Authorization: Bearer fe416b951aa24e21ac721bc65794ca6b
tenant-id: 1

{
  "id": "544449082769412096",
  "name": "租户15",
  "accountCount": "20",
  "contactName": "test1",
  "status": 0
}

### 更新租户 /admin-api/system/tenant/page
GET http://127.0.0.1:48080/admin-api/system/tenant/page?status=2&pageNum=1&pageSize=10
Content-Type: application/json
Authorization: Bearer 3e71f55ccc754ad99af737a899c1c9bd
tenant-id: 1

### 获得租户可分配数量 /admin-api/system/tenant/get-allocatable-count
GET http://127.0.0.1:48080/admin-api/system/tenant/get-allocatable-count
Content-Type: application/json
Authorization: Bearer e2c473e36664444f8e56abd1a8570ab9
tenant-id: 1

### 获得租户其他已有的用户数量 /admin-api/system/tenant/get-allocatable-count
GET http://127.0.0.1:48080/admin-api/system/tenant/get-exist-user-count?id=1
Content-Type: application/json
Authorization: Bearer e2c473e36664444f8e56abd1a8570ab9
tenant-id: 1

### 更新租户 /admin-api/system/tenant/page
GET http://127.0.0.1:48080/admin-api/system/tenant/get-by-website?website=tenant_20250811184245
Content-Type: application/json
Authorization: Bearer 3e71f55ccc754ad99af737a899c1c9bd
tenant-id: 1
