### 获取租户编号 /admin-api/system/get-id-by-name
GET http://127.0.0.1:48080/admin-api/system/tenant/simple-list
Authorization: Bearer eb33f553e1194b52935de6fcc6a3f4f5
### 创建租户 /admin-api/system/tenant/create
POST http://127.0.0.1:48080/admin-api/system/tenant/create
Content-Type: application/json
Authorization: Bearer d6c2b8f9cc18459aa544a52cdfb5b1b0
tenant-id: 1

{
  "name": "租户6",
  "accountCount": "50",
  "contactName": "test",
  "status": 0
}

### 更新租户 /admin-api/system/tenant/update
PUT http://127.0.0.1:48080/admin-api/system/tenant/update
Content-Type: application/json
Authorization: Bearer 58d972a2df1a40828d28e1e5cd19ab07
tenant-id: 1

{
  "id": "3385601779470176256",
  "name": "租户6",
  "accountCount": "30",
  "contactName": "test1",
  "status": 0
}

### 更新租户 /admin-api/system/tenant/page
GET http://127.0.0.1:48080/admin-api/system/tenant/page?pageNum=1&pageSize=10
Content-Type: application/json
Authorization: Bearer 5175dc025cca4770ae9b826c1a723a08
tenant-id: 1
