### 获取租户编号 /admin-api/system/get-id-by-name
GET http://127.0.0.1:48080/admin-api/system/tenant/simple-list
Authorization: Bearer eb33f553e1194b52935de6fcc6a3f4f5
### 创建租户 /admin-api/system/tenant/create
POST {{baseUrl}}/system/tenant/create
Content-Type: application/json
Authorization: Bearer {{token}}
tenant-id: {{adminTenantId}}

{
  "name": "OneBase",
  "contactName": "开发者",
  "contactMobile": "15601691300",
  "status": 0,
  "domain": "https://www.iocoder.cn",
  "packageId": 110,
  "expireTime": 1699545600000,
  "accountCount": 20,
  "username": "admin",
  "password": "123321"
}
