server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: onebase-plugin-testhost
  profiles:
    active: dev
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# OneBase 插件系统配置
onebase:
  plugin:
    enabled: true
    plugins-dir: ${plugin.base-dir:D:\cmsr\10_cmsr\CodingSpace\Java\onebase-v3-be\onebase-plugin\onebase-plugin-testhost\plugins}
    auto-load: true
    auto-start: true

# 日志配置
logging:
  level:
    root: INFO
    com.cmsr.onebase: DEBUG
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
