
import {
  Edit,
  Delete,
  MagicWand,
  WritingFluently,
  MoreApp,
  CheckOne,
  HamburgerButton,
  EditName,
  SettingTwo,
  MoveOne,
  AddFour,
  Repair,
  MoreFour,
  Clear,
  PeoplePlusOne,
  System,
  More,
  AddUser,
  GoOn,
  PeoplePlus,
  Find,
  Add,
  Reject,
  PersonalCollection,
  FullSelection,
  Redo,
  AlignTextMiddleOne,
  SettingOne,
  EditOne,
  EditTwo,
  AddOne,
  Check,
  Translate,
  Right,
  DeleteFour,
  EfferentThree,
  Undo,
  PeopleMinusOne,
  CloseOne,
  Modify,
  DeleteMode,
  DoubleRight,
  PeopleSearch,
  Left,
  EfferentFour,
  AfferentFour,
  AddMode,
  DeleteThree,
  DeleteThemes,
  PlayCycle,
  ShareThree,
  Close,
  AllApplication,
  Share,
  DeleteTwo,
  Like,
  DeleteFive,
  DoubleLeft,
  PeopleMinus,
  Newlybuild,
  DeleteOne,
  Afferent,
  ApplicationTwo,
  Unlike,
  DownloadFour,
  Back,
  UploadOne,
  AfferentThree,
  Anchor,
  AnchorRound,
  ArcDeTriomphe,
  AssemblyLine,
  Bad,
  BezierCurve,
  Bike,
  BranchOne,
  BrdigeThree,
  BridgeTwo,
  BulletMap,
  Bye,
  ChangeDateSort,
  ChartGraph,
  ChartHistogram,
  ChinesePavilion,
  ChurchOne,
  CityGate,
  CityOne,
  Clap,
  Come,
  ConceptSharing,
  ConnectionPointTwo,
  Cool,
  DatabaseCode,
  DatabaseDownload,
  DatabaseEnter,
  DatabaseFail,
  DatabaseLock,
  DatabasePosition,
  DatabaseSync,
  DatabaseTime,
  DataDisplay,
  DataLock,
  DataUser,
  Easy,
  Elevator,
  Escalators,
  FactoryBuilding,
  FingerprintTwo,
  Five,
  Flashlight,
  Four,
  Good,
  Gopro,
  HardDiskOne,
  Histogram,
  KagiMap,
  Kettle,
  Gamepad,
  Hdd,
  Lamp,
  Laptop,
  LeftBranch,
  LinkBreak,
  LinkCloudFaild,
  MaslowPyramids,
  Master,
  Memory,
  Microphone,
  MonumentOne,
  Mouse,
  NegativeDynamics,
  NetworkTree,
  Open,
  Pagoda,
  Palace,
  Parabola,
  Phone,
  Phonograph,
  Pie,
  Platte,
  Press,
  School,
  Shop,
  Six,
  Slide,
  Tower,
  Yep,
  Zoom
} from '@icon-park/react';

export const COMPONENT_GROUP_NAME = 'component-list';

export interface GridItem {
  id: string;
  type: string;
  displayName: string;
}

// 编辑器类型常量
export const EDITOR_TYPES = {
  FORM_EDITOR: 'form_editor',
  LIST_EDITOR: 'list_editor',
  PAGE_SETTING: 'page_setting',
  METADATA_MANAGE: 'metadata_manage',
  FLOW_EDITOR:'flow_editor',
  WORKBENCH_EDITOR: 'workbench_editor',
} as const;

// 编辑器类型联合类型
export type EditorType = (typeof EDITOR_TYPES)[keyof typeof EDITOR_TYPES];

export const operationIcon: string[] = [
  'edit',
  'delete',
  'magic-wand',
  'writing-fluently',
  'more-app',
  'check-one',
  'hamburger-button',
  'edit-name',
  'setting-two',
  'move-one',
  'add-four',
  'repair',
  'more-four',
  'clear',
  'people-plus-one',
  'system',
  'more',
  'add-user',
  'go-on',
  'people-plus',
  'find',
  'add',
  'reject',
  'personal-collection',
  'full-selection',
  'redo',
  'align-text-middle-one',
  'setting-one',
  'edit-one',
  'edit-two',
  'add-one',
  'check',
  'translate',
  'right',
  'delete-four',
  'efferent-three',
  'undo',
  'people-minus-one',
  'close-one',
  'modify',
  'delete-mode',
  'double-right',
  'people-search',
  'left',
  'efferent-four',
  'afferent-four',
  'add-mode',
  'delete-three',
  'delete-themes',
  'play-cycle',
  'share-three',
  'close',
  'all-application',
  'share',
  'delete-two',
  'like',
  'delete-five',
  'double-left',
  'people-minus',
  'newlybuild',
  'delete-one',
  'afferent',
  'application-two',
  'unlike',
  'download-four',
  'back',
  'upload-one',
  'afferent-three'
];


export const iconMap = {
  'edit': Edit,
  'delete': Delete,
  'magic-wand': MagicWand,
  'writing-fluently': WritingFluently,
  'more-app': MoreApp,
  'check-one': CheckOne,
  'hamburger-button': HamburgerButton,
  'edit-name': EditName,
  'setting-two': SettingTwo,
  'move-one': MoveOne,
  'add-four': AddFour,
  'repair': Repair,
  'more-four': MoreFour,
  'clear': Clear,
  'people-plus-one': PeoplePlusOne,
  'system': System,
  'more': More,
  'add-user': AddUser,
  'go-on': GoOn,
  'people-plus': PeoplePlus,
  'find': Find,
  'add': Add,
  'reject': Reject,
  'personal-collection': PersonalCollection,
  'full-selection': FullSelection,
  'redo': Redo,
  'align-text-middle-one': AlignTextMiddleOne,
  'setting-one': SettingOne,
  'edit-one': EditOne,
  'edit-two': EditTwo,
  'add-one': AddOne,
  'check': Check,
  'translate': Translate,
  'right': Right,
  'delete-four': DeleteFour,
  'efferent-three': EfferentThree,
  'undo': Undo,
  'people-minus-one': PeopleMinusOne,
  'close-one': CloseOne,
  'modify': Modify,
  'delete-mode': DeleteMode,
  'double-right': DoubleRight,
  'people-search': PeopleSearch,
  'left': Left,
  'efferent-four': EfferentFour,
  'afferent-four': AfferentFour,
  'add-mode': AddMode,
  'delete-three': DeleteThree,
  'delete-themes': DeleteThemes,
  'play-cycle': PlayCycle,
  'share-three': ShareThree,
  'close': Close,
  'all-application': AllApplication,
  'share': Share,
  'delete-two': DeleteTwo,
  'like': Like,
  'delete-five': DeleteFive,
  'double-left': DoubleLeft,
  'people-minus': PeopleMinus,
  'newlybuild': Newlybuild,
  'delete-one': DeleteOne,
  'afferent': Afferent,
  'application-two': ApplicationTwo,
  'unlike': Unlike,
  'download-four': DownloadFour,
  'back': Back,
  'upload-one': UploadOne,
  'afferent-three': AfferentThree
} as const;

export const appIconMap = {
  bike: Bike,
  'bullet-map': BulletMap,
  'church-one': ChurchOne,
  'data-display': DataDisplay,
  'fingerprint-two': FingerprintTwo,
  'arc-de-triomphe': ArcDeTriomphe,
  'brdige-three': BrdigeThree,
  'bridge-two': BridgeTwo,
  'chinese-pavilion': ChinesePavilion,
  'city-gate': CityGate,
  'city-one': CityOne,
  elevator: Elevator,
  escalators: Escalators,
  'factory-building': FactoryBuilding,
  'monument-one': MonumentOne,
  'link-cloud-faild': LinkCloudFaild,
  'network-tree': NetworkTree,
  'link-break': LinkBreak,
  'left-branch': LeftBranch,
  'connection-point-two': ConnectionPointTwo,
  'branch-one': BranchOne,
  'assembly-line': AssemblyLine,
  'bezier-curve': BezierCurve,
  'anchor-round': AnchorRound,
  anchor: Anchor,
  good: Good,
  four: Four,
  platte: Platte,
  five: Five,
  cool: Cool,
  clap: Clap,
  bad: Bad,
  bye: Bye,
  come: Come,
  easy: Easy,
  'concept-sharing': ConceptSharing,
  'data-lock': DataLock,
  'database-code': DatabaseCode,
  'data-user': DataUser,
  'database-download': DatabaseDownload,
  'database-enter': DatabaseEnter,
  'database-lock': DatabaseLock,
  'database-position': DatabasePosition,
  'database-time': DatabaseTime,
  'database-sync': DatabaseSync,
  'database-fail': DatabaseFail,
  slide: Slide,
  'negative-dynamics': NegativeDynamics,
  parabola: Parabola,
  pie: Pie,
  'maslow-pyramids': MaslowPyramids,
  'kagi-map': KagiMap,
  histogram: Histogram,
  'chart-histogram': ChartHistogram,
  'chart-graph': ChartGraph,
  'change-date-sort': ChangeDateSort,
  phonograph: Phonograph,
  phone: Phone,
  mouse: Mouse,
  microphone: Microphone,
  memory: Memory,
  master: Master,
  laptop: Laptop,
  lamp: Lamp,
  kettle: Kettle,
  Hdd: Hdd,
  gamepad: Gamepad,
  flashlight: Flashlight,
  gopro: Gopro,
  hardDiskOne: HardDiskOne,
  open: Open,
  press: Press,
  yep: Yep,
  zoom: Zoom,
  six: Six,
  pagoda: Pagoda,
  palace: Palace,
  shop: Shop,
  school: School,
  tower: Tower
};

export const iconColorList = ['#4E5969', '#00B42A', '#F53F3F', '#165DFF', '#FF7D00', '#C9CDD4'];
