server:
  port: 48080

--- #################### 数据库相关配置 ####################
spring:
  # 数据源配置项
  datasource:
    driver-class-name: com.kingbase8.Driver
    url: jdbc:kingbase8://10.0.104.30:54321/onebase_cloud_v3?currentSchema=public&useUnicode=true&characterEncoding=utf-8
    username: SYSTEM
    password: 3er4#ER$
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 1
      maximum-pool-size: 20
      connection-test-query: SELECT 1
      connection-timeout: 30000
      validation-timeout: 5000
  redis:
    redisson:
      config: |
        singleServerConfig:
          address: "redis://10.0.104.38:6379"
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 5
          connectionMinimumIdleSize: 2
          connectionPoolSize: 5
          database: 0
  # Redis 配置。Redisson 默认的配置足够使用，一般不需要进行调优
  data:
    redis:
      host: 10.0.104.38 # 地址
      #host: 127.0.0.1 # 地址
      port: 6379 # 端口
      database: 0 # 数据库索引
      #    password: dev # 密码，建议生产环境开启
      timeout: 30000ms # 超时时间
      connect-timeout: 30000 # 连接超时时间
      lettuce:
        pool:
          max-active: 24    # 最大连接数，与错误信息中的24保持一致
          max-idle: 2      # 最大空闲连接
          min-idle: 2       # 最小空闲连接
          max-wait: 10000ms # 最大等待时间
          time-between-eviction-runs: 30s # 空闲连接检查间隔

--- #################### 服务保障相关配置 ####################

# Lock4j 配置项
lock4j:
  acquire-timeout: 3000 # 获取分布式锁超时时间，默认为 3000 毫秒
  expire: 30000 # 分布式锁的超时时间，默认为 30 毫秒

# 日志文件配置
logging:
  file:
    name: ${user.home}/logs/${spring.application.name}.log # 日志文件名，全路径

debug: false

--- #################### OneBase相关配置 ####################

# OneBase配置项，设置当前项目所有自定义的配置
onebase:
  captcha:
    enable: false # 本地环境，暂时关闭图片验证码，方便登录等接口的测试；
  platform-tenant:
    enable-create-app: true # 测试环境，暂时允许平台租户创建应用，方便登录接口测试；
  security:
    mock-enable: false
  access-log: # 访问日志的配置项
    enable: false
  web:
    return-exception-stack-trace: true # 本地开发：接口错误时返回堆栈，便于调试
  scheduler:
    address: http://10.0.104.33:12345/dolphinscheduler
    token: 85806d2d33502cef3036fb30b320e5f5
    env: 154612656767296
    flow-project: 154702155517248
    flow-url: http://bing.com
    etl-project: 155572154738048
    tenant: root
  flink:
    address: http://10.0.104.30:58080

justauth:
  enabled: true
  cache:
    type: REDIS
    prefix: 'social_auth_state:' # 缓存前缀，目前只对 Redis 缓存生效，默认 JUSTAUTH::STATE::
    timeout: 24h # 超时时长，目前只对 Redis 缓存生效，默认 3 分钟

wx:
  mp: # 参见 https://github.com/Wechat-Group/WxJava/blob/develop/spring-boot-starters/wx-java-mp-spring-boot-starter/README.md 文档
    app-id: wx5b23ba7a5589ecbb # 测试号（自己的）
    secret: 2a7b3b20c537e52e74afd395eb85f61f
    # 存储配置，解决 AccessToken 的跨节点的共享
    config-storage:
      type: RedisTemplate # 采用 RedisTemplate 操作 Redis，会自动从 Spring 中获取
      key-prefix: wx # Redis Key 的前缀
      http-client-type: HttpClient # 采用 HttpClient 请求微信公众号平台
  miniapp: # 参见 https://github.com/Wechat-Group/WxJava/blob/develop/spring-boot-starters/wx-java-miniapp-spring-boot-starter/README.md 文档
    appid: wxc4598c446f8a9cb3 # 测试号（Kongdy 提供的）
    secret: 4a1a04e07f6a4a0751b39c3064a92c8b
    config-storage:
      type: RedisTemplate # 采用 RedisTemplate 操作 Redis，会自动从 Spring 中获取
      key-prefix: wa # Redis Key 的前缀
    http-client-type: HttpClient # 采用 HttpClient 请求微信公众号平台

liteflow:
  enable: true
rocketmq:
  endpoints: 10.0.104.38:8081

