### 环境配置说明
# 上面已设置默认的local环境变量，可直接运行
# 如需切换环境，请在IntelliJ IDEA中选择对应环境: local/gateway
# 或者手动修改上面的@变量值

### 请求 /get 接口 => 获取函数信息
GET {{baseUrl}}/tiangong/alert/get-latest-alerts
Authorization: Bearer {{token}}
tenant-id: {{adminTenantId}}