### 创建部门
POST {{baseUrl}}/corp/dept/create
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "test-dept",
  "parentId": 0,
  "leaderUserId": 1,
  "sort": 1,
  "status": 0
}

### 更新部门
POST {{baseUrl}}/corp/dept/update
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 1,
  "name": "test-dept-updated",
  "parentId": 0,
  "leaderUserId": 1,
  "sort": 1,
  "status": 0
}

### 修改部门用户管理员/主管
POST {{baseUrl}}/corp/dept/update-dept-admin-or-director
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "deptId": 1,
  "userId": 1,
  "updateType": "admin"
}

### 删除部门
POST {{baseUrl}}/corp/dept/delete?id=1
Authorization: Bearer {{token}}

### 获取部门列表
GET {{baseUrl}}/corp/dept/list?name=test&status=0
Authorization: Bearer {{token}}

### 获取部门精简信息列表
GET {{baseUrl}}/corp/dept/simple-list
Authorization: Bearer {{token}}

### 获得部门信息
GET {{baseUrl}}/corp/dept/get?id=1
Authorization: Bearer {{token}}

### 指定/搜索获取部门和用户信息
GET {{baseUrl}}/corp/dept/get-dept-users?deptId=1&searchKey=test
Authorization: Bearer {{token}}

### 根据ID和类型获取其所属部门及其父部门列表
GET {{baseUrl}}/corp/dept/get-depts-by-id?id=1&idType=user
Authorization: Bearer {{token}}

