import { FieldType, approvalResultOptions } from '../../constants';

export enum OperatorType {
  VALUE = 'value',
  VARIABLES = 'variables',
  FORMULA = 'formula'
}

export enum ElementType {
  INPUT = 'input',
  NUMBER = 'number',
  SCOPE = 'scope',
  DATE = 'date',
  DATE_RANGE = 'dateRange',
  SELECT = 'select',
  SELECT_MULTIPLE = 'selectMultiple',
  USER_SELECT = 'userSelect',
  USER_MULTIPLE = 'userMultiple'
}

export enum DateOperator {
  EQUALS = 'EQUALS',
  LATER_THAN = 'LATER_THAN',
  LATER_RANGE = 'LATER_RANGE'
}

interface ComplexInfoItem {
  type: ElementType;
  options: DateOperator | Array<{ label: string; value: string }>;
}

type ComplexInfo = Record<
  | 'DATETIME_EQUALS'
  | 'DATETIME_LATER_THAN'
  | 'DATETIME_RANGE'
  | 'DATA_SELECTION_EQUALS'
  | 'DATA_SELECTION_NOT_EQUALS'
  | 'DATA_SELECTION_CONTAINS'
  | 'USER_EQUALS',
  ComplexInfoItem
>;

export enum InputKeyType {
  TEXT_EQUALS = 'TEXT_EQUALS',
  TEXT_NOT_EQUALS = 'TEXT_NOT_EQUALS',
  TEXT_CONTAINS = 'TEXT_CONTAINS',
  TEXT_NOT_CONTAINS = 'TEXT_NOT_CONTAINS',
  TEXT_EXISTS_IN = 'TEXT_EXISTS_IN',
  TEXT_NOT_EXISTS_IN = 'TEXT_NOT_EXISTS_IN',
  LONG_TEXT_EQUALS = 'LONG_TEXT_EQUALS',
  LONG_TEXT_NOT_EQUALS = 'LONG_TEXT_NOT_EQUALS',
  LONG_TEXT_CONTAINS = 'LONG_TEXT_CONTAINS',
  LONG_TEXT_NOT_CONTAINS = 'LONG_TEXT_NOT_CONTAINS',
  EMAIL_EQUALS = 'EMAIL_EQUALS',
  EMAIL_NOT_EQUALS = 'EMAIL_NOT_EQUALS',
  EMAIL_CONTAINS = 'EMAIL_CONTAINS',
  EMAIL_NOT_CONTAINS = 'EMAIL_NOT_CONTAINS',
  EMAIL_EXISTS_IN = 'EMAIL_EXISTS_IN',
  EMAIL_NOT_EXISTS_IN = 'EMAIL_NOT_EXISTS_IN',
  PHONE_EQUALS = 'PHONE_EQUALS',
  PHONE_NOT_EQUALS = 'PHONE_NOT_EQUALS',
  PHONE_CONTAINS = 'PHONE_CONTAINS',
  PHONE_NOT_CONTAINS = 'PHONE_NOT_CONTAINS',
  PHONE_EXISTS_IN = 'PHONE_EXISTS_IN',
  PHONE_NOT_EXISTS_IN = 'PHONE_NOT_EXISTS_IN',
  URL_EQUALS = 'URL_EQUALS',
  URL_NOT_EQUALS = 'URL_NOT_EQUALS',
  URL_CONTAINS = 'URL_CONTAINS',
  URL_NOT_CONTAINS = 'URL_NOT_CONTAINS',
  ADDRESS_EQUALS = 'ADDRESS_EQUALS',
  ADDRESS_NOT_EQUALS = 'ADDRESS_NOT_EQUALS',
  ADDRESS_CONTAINS = 'ADDRESS_CONTAINS',
  ADDRESS_NOT_CONTAINS = 'ADDRESS_NOT_CONTAINS',
  AUTO_CODE_EQUALS = 'AUTO_CODE_EQUALS',
  AUTO_CODE_NOT_EQUALS = 'AUTO_CODE_NOT_EQUALS',
  AUTO_CODE_CONTAINS = 'AUTO_CODE_CONTAINS',
  AUTO_CODE_NOT_CONTAINS = 'AUTO_CODE_NOT_CONTAINS',
  AUTO_CODE_EXISTS_IN = 'AUTO_CODE_EXISTS_IN',
  AUTO_CODE_NOT_EXISTS_IN = 'AUTO_CODE_NOT_EXISTS_IN'
}

export enum NumberKeyType {
  NUMBER_EQUALS = 'NUMBER_EQUALS',
  NUMBER_NOT_EQUALS = 'NUMBER_NOT_EQUALS',
  NUMBER_GREATER_THAN = 'NUMBER_GREATER_THAN',
  NUMBER_GREATER_EQUALS = 'NUMBER_GREATER_EQUALS',
  NUMBER_LESS_THAN = 'NUMBER_LESS_THAN',
  NUMBER_LESS_EQUALS = 'NUMBER_LESS_EQUALS',
  AGGREGATE_EQUALS = 'AGGREGATE_EQUALS',
  AGGREGATE_NOT_EQUALS = 'AGGREGATE_NOT_EQUALS',
  AGGREGATE_GREATER_THAN = 'AGGREGATE_GREATER_THAN',
  AGGREGATE_GREATER_EQUALS = 'AGGREGATE_GREATER_EQUALS',
  AGGREGATE_LESS_THAN = 'AGGREGATE_LESS_THAN',
  AGGREGATE_LESS_EQUALS = 'AGGREGATE_LESS_EQUALS',
  ID_EQUALS = 'ID_EQUALS',
  ID_NOT_EQUALS = 'ID_NOT_EQUALS'
} // 数字输入框

export enum ScopeKeyType {
  AGGREGATE_RANGE = 'AGGREGATE_RANGE'
} // 数字范围

export const VARIABLE_MAP: Partial<Record<FieldType, FieldType[]>> = {
  [FieldType.TEXT]: [FieldType.TEXT, FieldType.LONG_TEXT, FieldType.EMAIL, FieldType.PHONE, FieldType.URL]
};

export const ComplexInfo: ComplexInfo = {
  DATETIME_EQUALS: {
    type: ElementType.DATE,
    options: DateOperator.EQUALS
  },
  DATETIME_LATER_THAN: {
    type: ElementType.DATE,
    options: DateOperator.LATER_THAN
  },
  DATETIME_RANGE: {
    type: ElementType.DATE_RANGE,
    options: DateOperator.LATER_RANGE
  },
  DATA_SELECTION_EQUALS: {
    type: ElementType.SELECT,
    options: approvalResultOptions
  },
  DATA_SELECTION_NOT_EQUALS: {
    type: ElementType.SELECT,
    options: approvalResultOptions
  },
  DATA_SELECTION_CONTAINS: {
    type: ElementType.SELECT_MULTIPLE,
    options: approvalResultOptions
  },
  USER_EQUALS: {
    type: ElementType.USER_SELECT,
    options: []
  }
};
